# Generated by Django 4.1.1 on 2022-10-12 14:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descriptions', models.TextField(max_length=800)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='hill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('volume', models.CharField(max_length=3)),
                ('cinema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('stars', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('descriptions', models.TextField(max_length=800)),
                ('pictures', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.hill')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.movie')),
            ],
        ),
    ]
