# Generated by Django 4.1.2 on 2022-10-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_cinemauser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='pictures',
        ),
    ]
